### ISSUE TITLE
What is the license of the code

### ISSUE THREAD

**Issue by french-paragon** [chashikajw/simplex-algorithm#4]
Hi, how are you ?

I am searching for an implementation of the simplex in c++ for a project of mine. Your code looks like a good option but it is lacking a license, so I am not sure if I can re-use it or not, and under which conditions.

Could you add a license to the repository to makes things clearer ?

**Comment by chashikajw** [comment]
This repo has [Apache 2.0 license](https://github.com/chashikajw/simplex-algorithm/blob/master/LICENSE).
